name: jchriscook
favicon: null
layout_spectrum: 0.31490468676202
typography_spectrum: 0.363510437309742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.508444776525721
  lightness: 0.7909518524538726
  saturation: 0.9761519955936819
  rhythmicContrast: 0.4188420050777495
purpose: []
