name: jchriscook
favicon: null
layout_spectrum: 0.91068
typography_spectrum: 0.32684
title: The Creative Laboratory
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5b8cc'
    - '#080609'
    - '#2a3f5e'
    - '#6e7f95'
    - '#49100b'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
